# Setup
title:        LZXprogrammer
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "zh_CN"

# About/contact
author:
  name:       Zhenxing Liu
  url:        LZXprogrammer.github.io
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


host: 0.0.0.0