# Setup
title:        LZXprogrammer@Blog
tagline:      一个不知道写点什么东西的博客
baseurl:      ""
paginate:     1
locale:       "zh_CN"

# About/contact
author:
  name:       Zhenxing Liu
  url:        LZXprogrammer.github.io
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown


host: 0.0.0.0